// Copyright © 2026 Fazlul Shahriar. All rights reserved.
// Use of this source code is governed by the MIT License
// that can be found in the LICENSE file.

// Package gendoc generates and validates doc.go files from usage text.
package gendoc

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"strings"
	"testing"
)

// Check verifies that doc.go is up to date with the given usage text.
// If fix is true, it writes the updated doc.go instead of failing.
// The genCmd is used in the stale error message to tell the user how
// to regenerate (e.g. "go generate ./cmd/acme-acp").
func Check(t *testing.T, usageText string, fix bool, genCmd string) {
	t.Helper()

	buf := generate(usageText)
	formatted, err := format.Source(buf)
	if err != nil {
		t.Fatalf("format.Source: %v", err)
	}

	const docPath = "doc.go"
	old, err := os.ReadFile(docPath)
	if err != nil && !os.IsNotExist(err) {
		t.Fatalf("reading %s: %v", docPath, err)
	}

	if bytes.Equal(old, formatted) {
		t.Logf("%s is up to date.", docPath)
		return
	}

	if fix {
		if err := os.WriteFile(docPath, formatted, 0666); err != nil {
			t.Fatal(err)
		}
		t.Logf("wrote %d bytes to %s", len(formatted), docPath)
	} else {
		t.Errorf("%s is stale. To update, run '%s'.", docPath, genCmd)
	}
}

func generate(text string) []byte {
	var buf bytes.Buffer
	fmt.Fprintln(&buf, "// Code generated by 'go generate'; DO NOT EDIT.")
	fmt.Fprintln(&buf)
	for _, line := range strings.Split(strings.TrimRight(text, "\n"), "\n") {
		if line == "" {
			fmt.Fprintln(&buf, "//")
		} else {
			fmt.Fprintf(&buf, "// %s\n", line)
		}
	}
	fmt.Fprintln(&buf, "package main")
	return buf.Bytes()
}
