// Code generated by 'go generate'; DO NOT EDIT.

// Acme-mcp is an MCP server that communicates over standard
// input/output.  It exposes the following tools for manipulating
// Acme windows:
//
//   - list_windows — list all open windows
//   - get_body, set_body, append_body — read or write window body
//   - get_tag, set_tag — read or write the window tag
//   - get_addr, set_addr — get or set the address (dot)
//   - get_selection — get selected text
//   - replace_text — replace text matched by an address expression
//   - create_window, delete_window — create or delete windows
//   - send_ctl — send control messages (show, clean, dirty, etc.)
//   - get_window_info — get window metadata (size, font, tab width)
//
// Usage:
//
//	acme-mcp
package main
